Documentation
ev-chik/geometric_lib pull request #3
Opened 2024-10-04 17:47 UTC by ev-chik

Closes #2

2024-10-04 18:02 UTC, ev-chik commented
Чикадзе Евгений Александрович
М3114

2024-10-05 12:29 UTC, Kkkkkk58 requested changes
неправильно выбрана исходная ветка - напрямую из релизной ветки в gitflow фичи не отводятся

2024-10-05 13:42 UTC, ev-chik commented
> неправильно выбрана исходная ветка - напрямую из релизной ветки в gitflow фичи не отводятся

Но ведь это не фича. Какую бы я статью про gitflow не открыл, там написано, что работа с документацией проводится на ветке release

2024-10-05 14:44 UTC, Kkkkkk58 commented
> > неправильно выбрана исходная ветка - напрямую из релизной ветки в gitflow фичи не отводятся
> 
> Но ведь это не фича. Какую бы я статью про gitflow не открыл, там написано, что работа с документацией проводится на ветке release. Примеры: https://habr.com/ru/companies/yandex_praktikum/articles/812139/ https://bitworks.software/2019-03-12-gitflow-workflow.html

Теперь понял задумку. Если подходить к этому, как к документации к конкретному релизу (Patch Notes, например), то да, валидно.
В задаче лабораторной такого не закладывалось, но соглашусь, что трактовать можно было по-разному, так как явного указания на обратное не было.

Баллы выставил

2024-10-05 14:45 UTC, Kkkkkk58 approved these changes

2024-10-05 19:34 UTC, ev-chik commented
> > > неправильно выбрана исходная ветка - напрямую из релизной ветки в gitflow фичи не отводятся
> > 
> > 
> > Но ведь это не фича. Какую бы я статью про gitflow не открыл, там написано, что работа с документацией проводится на ветке release. Примеры: https://habr.com/ru/companies/yandex_praktikum/articles/812139/ https://bitworks.software/2019-03-12-gitflow-workflow.html
> 
> Теперь понял задумку. Если подходить к этому, как к документации к конкретному релизу (Patch Notes, например), то да, валидно. В задаче лабораторной такого не закладывалось, но соглашусь, что трактовать можно было по-разному, так как явного указания на обратное не было.
> 
> Баллы выставил

Благодарю. Если будет время и возможность, сможете написать, как ещё можно было трактовать задание? Просто у меня именно такое однозначное понимание сложилось, и я не очень понимаю, как можно подойти к этому иначе

2024-10-16 09:22 UTC, merged